### ISSUE TITLE
Multiple Paths in --module-path not supported

### ISSUE THREAD

**Issue by brcolow** [raydac/mvn-jlink#1]
Hello,

I have two issues, actually.

1.) It seems that specifying more than one directory for --module-path is not supported. For example:

`<modulePath>${jlink.jdk.path}${file.separator}jmods;target/</modulePath>`

This is because in:

```java
commandLineOptions.add("--module-path");
    if (this.modulePath != null) {
      log.debug("Detected non-empty module path in configuration: " + this.modulePath);

      final File modulePathFolder = new File(this.modulePath);

      if (!modulePathFolder.isDirectory()) {
        throw new MojoExecutionException("Can't find folder provided in 'modulePath': " + modulePathFolder.getAbsolutePath());
      }
```

It does not split the path on either `:` or `;` (depending on if it's *nix or Windows) and check each element of the module path individually.

It would be nice if the plugin provided some property that is either `;` or `:` depending on the OS running Maven (so that the POM is cross-platform) that could be used inside the module-path, but that's a secondary concern.

2.) Not sure if this is an issue with the plugin, but when trying to add the following option:

`<option>--launcher bootstrap=com.dow.aws.lambda/com.dow.aws.lambda.Bootstrap</option>`

I get the following error from jlink:

```
[ERROR] Error: unknown option: --launcher bootstrap=com.dow.aws.lambda/com.dow.aws.lambda.Bootstrap
Usage: jlink <options> --module-path <modulepath> --add-modules <module>[,<module>...]
Use --help for a list of possible options
```

It maybe could be because of the space?

Thanks very much for your useful plugin!

**Comment by raydac** [comment]
thank you very much for your report, I will investigate the first issue and what about the second one - try to split it as two option items
```xml
<options>
   <option>--launcher</option>
   <option>bootstrap=com.dow.aws.lambda/com.dow.aws.lambda.Bootstrap</option>
</options>
```

**Comment by raydac** [comment]
I made changes and have replaced single string  `modulePath` parameter by string list `modulePaths`, so you can try snapshot with such snippet
```xml
<modulePaths>
   <path>JDK.PROVIDER.JMODS</path>
   <path>target/</path>
</modulePaths>
```
path to the provider's jmods folder can be marked through pseudo-path `JDK.PROVIDER.JMODS`

**Comment by raydac** [comment]
I don't public snapshots in any repository, just clone project and build it locally, snapshot will be represented in your local maven repository

**Comment by raydac** [comment]
yes, sorry there is a some bug, try now

**Comment by raydac** [comment]
JDK.PROVIDER.JMODS uses path to jdk provider defined for `jlink` goal, if you use the pom which provided in the issue then your `cache-jdk` has downloaded one JDK and `jlink` uses default JDK which is same as maven uses. Usually `cache-jdk` is good if you make cross-platform java images, if you build for same host-os then you can avoid `cache-jdk`
