### ISSUE TITLE
JDK-Tool falsely assumes extension of required tool.

### ISSUE THREAD

**Issue by Jai-2001** [raydac/mvn-jlink#10]
Running the JDK-Tool stage on Windows assumes that the extension of the desired tool will be ".exe", while some tools are known to use other extensions, such .cmd. This can be reproduced by caching a version of GraalVM, and attempting to run the "gu" tool which results in the following error.
```
[INFO] --- mvn-jlink-wrapper:1.2.0:jdk-tool (call-tool) @ {PACKAGE_NAME}---
[ERROR] Can't find file: C:\Users\{USERNAME}\.jdks\graalvm-ce-19\bin\gu.exe
```

**Comment by raydac** [comment]
aqnd could you provide some example of your pom to recognize how you make a call to the "gu" tool?

**Comment by raydac** [comment]
I've made some improvements in 1.2.1_SNAPSHOT so you can provide specific extenstion for selected OS
```xml
<forceOsExtensions>
   <windows>cmd</windows>
</forceOsExtensions>
```
just provide the parameter for task where you call gu.cmd and it will be using cmd extension
