### ISSUE TITLE
MAC OS never detected

### ISSUE THREAD

**Issue by TomVanWemmel** [raydac/mvn-jlink#13]
I've been using mvn-jlink-wrapper on my machine with the following config
```
<provider>ADOPTIUM</provider>
<providerConfig>
    <repositoryName>temurin21-binaries</repositoryName>
    <version>21U</version>
    <arch>x64</arch>
    <type>jdk</type>
    <impl>hotspot</impl>
    <build>2024-01-14-11-20</build>
</providerConfig>
```

Unfortunately, on my Mac this fails unless I specifically put the `<os>mac</os>` configuration. 
Instead the wrapper tries to download the `unix` binary. 
This is caused by the following code: 
```
public static HostOs findHostOs() {
  return VALUES.stream().filter(x -> x != UNKNOWN).filter(HostOs::isHostOs).findFirst()
      .orElse(UNKNOWN);
}
```
The resulting HostOs will be `UNIX` because `org.apache.commons.lang3.SystemUtils.IS_OS_UNIX` delegates to `IS_OS_MAC_OSX`. 

Furthermore, even if it would detect the right OS, the id needs to be `mac` and not `macos` or `macosx` for the Adoptium provider.

**Comment by raydac** [comment]
I have made some improvements, you can try SNAPSHOT

**Comment by TomVanWemmel** [comment]
The snapshot version still chooses unix in my case. 
I believe [this commit](https://github.com/raydac/mvn-jlink/commit/7be62e374e719aa2d9cdf9445498ec8b61e6310c) would also create the same issue for Linux, because `SystemUtils.IS_OS_UNIX` also includes `IS_OS_LINUX`
```
public static final boolean IS_OS_UNIX = IS_OS_AIX || IS_OS_HP_UX || IS_OS_IRIX || IS_OS_LINUX || IS_OS_MAC_OSX
            || IS_OS_SOLARIS || IS_OS_SUN_OS || IS_OS_FREE_BSD || IS_OS_OPEN_BSD || IS_OS_NET_BSD;
```

**Comment by raydac** [comment]
you are right, I have made some improvements in detection of host os and added extra test, you can try SNAPSHOT

**Comment by TomVanWemmel** [comment]
Yes, works perfectly now!
Thank you for the effort, really appreciate it :)

**Comment by raydac** [comment]
1.2.3 version with the fix has been released
