### ISSUE TITLE
[ADOPTIUM] `jdk-17.0.12_7` can't be installed

### ISSUE THREAD

**Issue by cimnine** [raydac/mvn-jlink#15]
The following pattern does not match any artifacts of the [`jdk-17.0.12_7` temurin](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.12%2B7) release. Hence, this JDK/JRE can't be downloaded. See https://regexr.com/85his.

https://github.com/raydac/mvn-jlink/blob/3ec37b4b4e9b3ee3efc275b9f961a1626194d59f/mvn-jlink-wrapper/src/main/java/com/igormaznitsa/mvnjlink/jdkproviders/providers/AdoptiumOpenJdkProvider.java#L375-L377

A quick fix might be to use [the following improved pattern](https://regexr.com/85hj8). Though I can't say how it behaves with JDK versions other than the specific one I've tested.

```regex
^OpenJDK([\da-z]*)-([a-z-]+)_([0-9a-z\-]+)_([0-9a-z-]+)_([0-9a-z_]+)_([\-a-z0-9]+(?:[._\-][0-9][a-z0-9]*)+(?:-metadata)?)\.([a-z0-9.]+)$
```

A more sustainable approach might be to use the Adoptium API, as I describe in #14.

**Comment by raydac** [comment]
fixed in 1.2.4
