### ISSUE TITLE
Add Support for AdoptOpenJDK Github Releases

### ISSUE THREAD

**Issue by brcolow** [raydac/mvn-jlink#2]
Hello,

I have found that many releases are made to the following Github repositories for AdoptOpenJDK:

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases
https://github.com/AdoptOpenJDK/openjdk12-binaries/releases
https://github.com/AdoptOpenJDK/openjdk13-binaries/releases

etc.

There are many more releases available than on the official AdoptOpenJDK website. I think that adding support to pull JVMs from these sources (via the cache-jdk task) may offer more options for builds.

Let me know what you think.

Thanks!

**Comment by raydac** [comment]
I have added ADOPTGIT provider, you can try, [example can be found here](https://github.com/raydac/mvn-jlink/tree/master/mvn-jlink-tests/mvn-jlink-test-adoptgit)

**Comment by brcolow** [comment]
You work very fast! Thanks so much for your work. I will be trying this soon.

**Comment by raydac** [comment]
all is ok, does it work well?

**Comment by brcolow** [comment]
It works great. Thank you.
