### ISSUE TITLE
Path to javac executable

### ISSUE THREAD

**Issue by mzorba** [raydac/mvn-jlink#4]
Hello,

First of all, thank you for implementing this useful plugin.

I am trying to use it for automatically downloading JDK during the build. It works as expected.
I am getting path to Adopt OPenJDK download location in jdkPathProperty. The issue I am having is finding absolute path to javac executable on different OS. Each Adopt OS distribution and even version has different structure. MacOS has "Contents/Home", Windows does not.

Do you maybe have a suggestion how to do this, is the plugin itself able to expose it, since if I am correct there is logic inside for locating executables?

Thank you,
Miro

**Comment by raydac** [comment]
I have improved  `cache-jdk` mojo, added feature to search files in cached JDK root through ANT patterns and place found paths as project properties, you can try it in 1.0.6-SNAPSHOT in the case just provide patterns for needed files and they will be found and added in project properties
```xml
 <pathAsProperty>
    <jdk.javac.file>/**/javac</jdk.javac.file>
    <jdk.jstat.file>/**/jstat</jdk.jstat.file>
    <jdk.jexec.file>/**/lib/jexec*</jdk.jexec.file>
 </pathAsProperty>
 ```

**Comment by mzorba** [comment]
Wow, that was fast 👍.
It works, thanks a lot.

Regards,
Miro

**Comment by raydac** [comment]
added into release 1.0.6
