### ISSUE TITLE
Github API rate limits error

### ISSUE THREAD

**Issue by strump** [raydac/mvn-jlink#5]
When I try to build [Milkman](https://github.com/warmuuh/milkman/) project Maven fails at `com.github.warmuuh.mvn-jlink` plugin with error:

```
Can't doLoad SDK archive from https://api.github.com/repos/bell-sw/Liberica/releases?per_page=100&page=1 : 403 Forbidden
```

Github server gives response:

```javascript
{
  "message": "API rate limit exceeded for XXX.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Is there any way to provide authentication in plugin configuration to overcome server rate limit?

**Comment by raydac** [comment]
As I see in github doc, you have 60 downloads per hour as anonymous one, but they limit through IP address and may be it takes part. At present there is not any way in plugin to provide git credentials, I will add such functionality

**Comment by raydac** [comment]
I have added logging for limit remaining fields in response
